"""empty message

Revision ID: 919b95999fe8
Revises: 7ef885219b0b
Create Date: 2023-01-19 18:48:24.845066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '919b95999fe8'
down_revision = '7ef885219b0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))

    op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')

    op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
